# fly.toml app configuration file generated for ai-agency on 2026-03-08T13:12:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-agency'
primary_region = 'nrt'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://olmwsmrewylwsxhhubvm.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sbXdzbXJld3lsd3N4aGh1YnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NDI1NTAsImV4cCI6MjA4ODUxODU1MH0.6qvtk9NvVgmj7Kjj-ou0CXqdEPg31U3N5iF60QrQO54"
    NEXT_PUBLIC_APP_URL = "https://ai-agency.fly.dev"

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
